export const categoriesData = [
  {
    id: 1,
    path: "./assets/images/vihicle_insurance_icon.svg",
    text: <>Passenger-Carrying <br/> Vehicle Insurance</>,
    altText: "Passenger-Carrying Vehicle Insurance",
  },
  {
    id: 2,
    path: "./assets/images/goods_carrying_icon.svg",
    text: <>Goods-Carrying <br/> Vehicle Insurance</>,
    altText: "Goods-Carrying Vehicle Insurance",
  },
  {
    id: 3,
    path: "./assets/images/two_wheeler_icon.svg",
    text: <>Two-wheeler<br/> Insurances</>,
    altText: "Two-wheeler Insurances",
  },
  {
    id: 4,
    path: "./assets/images/car_insurance_icon.svg",
    text: <>Car <br/> Insurance</>,
    altText: "Car Insurance",
  },
  {
    id: 5,
    path: "./assets/images/ev_insurance_icon.svg",
    text: <>EV <br/> Insurance</>,
    altText: "EV Insurance",
  },
  {
    id: 6,
    path: "./assets/images/marine_icon.svg",
    text: <>Marine  <br/> Insurance</>,
    altText: "Marine Insurance",
  },
  {
    id: 7,
    path: "./assets/images/aviation_icon.svg",
    text: <>Aviation  <br/> Insurance</>,
    altText: "Aviation  Insurance",
  },
  {
    id: 8,
    path: "./assets/images/health_insurance_icon.svg",
    text: <>Health <br/> Insurance</>,
    altText: "Health Insurance",
  },
  {
    id: 9,
    path: "./assets/images/bussiness_insurense_icon.svg",
    text: <>Business <br/> Insurance</>,
    altText: "Business Insurance",
  },
  {
    id: 10,
    path: "./assets/images/life_insurence_icon.svg",
    text: <>Life <br/> Insurance</>,
    altText: "Life Insurance",
  },
  {
    id: 11,
    path: "./assets/images/travel_insurence_icon.svg",
    text: <>Travel <br/> Insurance</>,
    altText: "Travel  Insurance",
  },
  {
    id: 12,
    path: "./assets/images/personal_acciedent_icon.svg",
    text: <>Personal Accident <br/> Insurance</>,
    altText: "Personal Accident Insurance",
  },
  {
    id: 13,
    path: "./assets/images/home_insurance_icon.svg",
    text: <>Home <br/> Insurance</>,
    altText: "Home Insurance",
  },
  {
    id: 14,
    path: "./assets/images/cyber_crime_insurence.svg",
    text: <>Cyber Crime<br/> Insurance</>,
    altText: "Cyber Crime Insurance",
  },
];
